-- 3 Chillies — seed menu (80 items). Run AFTER schema.sql.
insert into public.menu_items (name, price, type, category, "desc") values
  ('Veg Corn Soup', 149, 'veg', 'Soups', 'Silky sweet-corn broth with crunch.'),
  ('Veg Hot And Sour Soup', 149, 'veg', 'Soups', 'Tangy, peppery and warming.'),
  ('Chicken Corn Soup', 159, 'nonveg', 'Soups', 'Creamy corn broth with shredded chicken.'),
  ('Chicken Hot And Sour Soup', 159, 'nonveg', 'Soups', 'Spicy-sour classic with chicken.'),
  ('Paneer Tikka (7 Pcs)', 309, 'veg', 'Tandoori Starters', 'Chargrilled cottage cheese, smoky spices.'),
  ('Achari Paneer Tikka (7 Pcs)', 309, 'veg', 'Tandoori Starters', 'Pickle-spiced tandoori paneer.'),
  ('Boneless Peri Peri Chicken (7 Pcs)', 439, 'nonveg', 'Tandoori Starters', 'Fiery peri-peri grilled chicken.'),
  ('Boneless Chicken Tikka (7 Pcs)', 439, 'nonveg', 'Tandoori Starters', 'Classic tandoori chicken tikka.'),
  ('Boneless Lehsuni Murgh Tikka (7 Pcs)', 439, 'nonveg', 'Tandoori Starters', 'Garlic-marinated chicken tikka.'),
  ('Fish Tikka (8 Pcs)', 439, 'nonveg', 'Tandoori Starters', 'Spiced tandoori fish.'),
  ('Boneless Guntur Kebab (7 Pcs)', 439, 'nonveg', 'Tandoori Starters', 'Guntur-chilli fired kebab.'),
  ('Paneer Butter Masala', 309, 'veg', 'Veg Main Course', 'Paneer in silky tomato-butter gravy.'),
  ('Palak Paneer', 309, 'veg', 'Veg Main Course', 'Cottage cheese in creamy spinach.'),
  ('Veg Kundan Masala', 349, 'veg', 'Veg Main Course', 'Rich mixed-veg house special.'),
  ('Kadhai Paneer', 249, 'veg', 'Veg Main Course', 'Wok-tossed paneer with peppers.'),
  ('Palak Masala', 309, 'veg', 'Veg Main Course', 'Spiced spinach masala.'),
  ('Dal Fry', 309, 'veg', 'Veg Main Course', 'Tempered yellow lentils.'),
  ('Aloo Gobi', 189, 'veg', 'Veg Main Course', 'Potato & cauliflower masala.'),
  ('Dal Tadka', 189, 'veg', 'Veg Main Course', 'Lentils with smoky tempering.'),
  ('Butter Chicken', 369, 'nonveg', 'Non Veg Main Course', 'Tandoori chicken in creamy makhani.'),
  ('Nawabi Chicken', 309, 'nonveg', 'Non Veg Main Course', 'Royal, mildly-spiced curry.'),
  ('Chicken Lababdar', 309, 'nonveg', 'Non Veg Main Course', 'Tomato-onion chicken curry.'),
  ('Chicken Tikka Masala', 209, 'nonveg', 'Non Veg Main Course', 'Grilled tikka in masala gravy.'),
  ('Kadhai Chicken', 309, 'nonveg', 'Non Veg Main Course', 'Peppery wok chicken.'),
  ('Chatpata Chicken', 309, 'nonveg', 'Non Veg Main Course', 'Tangy, spicy chicken.'),
  ('Plain Naan', 39, 'veg', 'Breads', 'Tandoor-baked flatbread.'),
  ('Butter Naan', 39, 'veg', 'Breads', 'Buttered soft naan.'),
  ('Garlic Naan', 49, 'veg', 'Breads', 'Garlic-butter naan.'),
  ('Kaju Rice', 189, 'veg', 'Rice', 'Cashew-studded rice.'),
  ('Plain Rice', 149, 'veg', 'Rice', 'Steamed basmati.'),
  ('Jeera Rice', 159, 'veg', 'Rice', 'Cumin-tempered rice.'),
  ('Paneer 65', 149, 'veg', 'Chinese', 'Crispy spiced paneer.'),
  ('Veg Manchurian', 149, 'veg', 'Chinese', 'Veg balls in tangy sauce.'),
  ('Chilli Paneer', 149, 'veg', 'Chinese', 'Wok-tossed paneer & peppers.'),
  ('Honey Chilli Potato', 149, 'veg', 'Chinese', 'Sweet-spicy crispy potatoes.'),
  ('Diced Paneer', 149, 'veg', 'Chinese', 'Diced paneer, chilli-garlic.'),
  ('Chicken 65', 309, 'nonveg', 'Chinese', 'South-Indian fried chicken.'),
  ('Chilli Chicken', 309, 'nonveg', 'Chinese', 'Indo-Chinese chilli chicken.'),
  ('Chicken Thai Pai', 309, 'nonveg', 'Chinese', 'Thai-style chicken.'),
  ('Dice Chicken', 309, 'nonveg', 'Chinese', 'Diced chilli chicken.'),
  ('Chicken Lollipop', 309, 'nonveg', 'Chinese', 'Frenched chicken wings.'),
  ('Pepper Chicken', 309, 'nonveg', 'Chinese', 'Black-pepper chicken.'),
  ('Pepper Fish', 309, 'nonveg', 'Chinese', 'Peppery fried fish.'),
  ('Loose Prawns', 369, 'nonveg', 'Chinese', 'Wok-tossed prawns.'),
  ('Golden Fried Prawns', 369, 'nonveg', 'Chinese', 'Crisp golden prawns.'),
  ('Corn Fish', 309, 'nonveg', 'Chinese', 'Fish with corn crumb.'),
  ('Thread Chicken (8 Pcs)', 369, 'nonveg', 'Chinese', 'Crispy thread-wrapped chicken.'),
  ('Veg Soft Fried Rice', 189, 'veg', 'Fried Rice', 'Soft-style veg fried rice.'),
  ('Veg Fried Rice', 189, 'veg', 'Fried Rice', 'Classic veg fried rice.'),
  ('Veg Schezwan Fried Rice', 199, 'veg', 'Fried Rice', 'Spicy schezwan rice.'),
  ('Veg Bandi Style Fried Rice', 189, 'veg', 'Fried Rice', 'Street-style fried rice.'),
  ('Veg Chilli Garlic Fried Rice', 199, 'veg', 'Fried Rice', 'Chilli-garlic fried rice.'),
  ('Egg Fried Rice', 189, 'nonveg', 'Fried Rice', 'Egg fried rice.'),
  ('Non Veg Schezwan Fried Rice', 219, 'nonveg', 'Fried Rice', 'Spicy chicken schezwan rice.'),
  ('Non Veg Soft Fried Rice', 209, 'nonveg', 'Fried Rice', 'Soft-style chicken rice.'),
  ('Non Veg Bandi Style Fried Rice', 209, 'nonveg', 'Fried Rice', 'Street-style chicken rice.'),
  ('Non Veg Chilli Garlic Fried Rice', 219, 'nonveg', 'Fried Rice', 'Chilli-garlic chicken rice.'),
  ('Veg Noodles', 189, 'veg', 'Noodles', 'Classic veg noodles.'),
  ('Veg Schezwan Noodles', 199, 'veg', 'Noodles', 'Spicy schezwan noodles.'),
  ('Veg Soft Noodles', 189, 'veg', 'Noodles', 'Soft-style veg noodles.'),
  ('Veg Exotic Noodles', 189, 'veg', 'Noodles', 'Exotic veg noodles.'),
  ('Veg Hakka Noodles', 189, 'veg', 'Noodles', 'Hakka-style noodles.'),
  ('Veg Bandi Style Noodles', 189, 'veg', 'Noodles', 'Street-style noodles.'),
  ('Veg Chilli Garlic Noodles', 199, 'veg', 'Noodles', 'Chilli-garlic noodles.'),
  ('Veg American Chopsuey Noodles', 219, 'veg', 'Noodles', 'Crispy noodles, sweet-tangy sauce.'),
  ('Egg Noodles', 189, 'nonveg', 'Noodles', 'Egg noodles.'),
  ('Non Veg Soft Noodles', 209, 'nonveg', 'Noodles', 'Soft chicken noodles.'),
  ('Non Veg Schezwan Noodles', 219, 'nonveg', 'Noodles', 'Spicy chicken schezwan noodles.'),
  ('Non Veg Exotic Noodles', 209, 'nonveg', 'Noodles', 'Exotic chicken noodles.'),
  ('Non Veg Hakka Noodles', 209, 'nonveg', 'Noodles', 'Hakka chicken noodles.'),
  ('Non Veg Bandi Style Noodles', 209, 'nonveg', 'Noodles', 'Street-style chicken noodles.'),
  ('Non Veg Chilli Garlic Noodles', 219, 'nonveg', 'Noodles', 'Chilli-garlic chicken noodles.'),
  ('Crispy Corn', 149, 'veg', 'Snacks', 'Golden crispy spiced corn.'),
  ('Apricot Delight', 189, 'veg', 'Desserts', 'Warm apricot with cream.'),
  ('Cream Fruit', 189, 'veg', 'Desserts', 'Fresh fruit in sweet cream.'),
  ('Virgin Mojito', 129, 'veg', 'Beverages', 'Mint-lime cooler.'),
  ('Sunset Cooler Mocktail', 129, 'veg', 'Beverages', 'Citrus sunset blend.'),
  ('Tropical Berry Mocktail', 129, 'veg', 'Beverages', 'Berry-tropical fizz.'),
  ('Blue Lagoon Mocktail', 129, 'veg', 'Beverages', 'Cool blue lemonade.'),
  ('Sea Breeze Mocktail', 129, 'veg', 'Beverages', 'Cranberry-citrus refresher.');
